name: 30분마다 환율 자동 업데이트

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # 여기서부터 중요! 전체 작업(Job) 수준에서 환경 변수를 선언합니다.
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

    steps:
      - name: 저장소 코드 불러오기
        uses: actions/checkout@v4

      - name: 파이썬(Python 3.10) 설치
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 필요한 라이브러리 설치
        run: |
          pip install pandas requests selenium webdriver-manager

      - name: 환율 크롤러 실행
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python exchange_crawler.py
